### ISSUE TITLE
server-up.sh doesn't work on Macs with Apple silicon chip

### ISSUE THREAD

**Issue by MathuC** [GEO-BON/bon-in-a-box-pipeline-engine#85]
**Describe the bug**
server-up.sh results in an error on macs with M2 chips: 
```
no matching manifest for linux/arm64/v8 in the manifest list entries
FAILED
```
This also seem to happen on the M1 chip according to [stackoverflow](https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8)

**System Information**
```
Operating System: macOS 14.1.2
Model Name: MacBook Air
Chip: Apple M2
Total Number of Cores: 8
Memory: 8 GB
```

**Comment by jmlord** [comment]
Adding this to compose.env.yml is a valid workaround:
```
  tiler:
    platform: linux/x86_64
```

I will automate this somewhere in the server.
